### ISSUE TITLE
Anti AFK 

### ISSUE THREAD

**Issue by jmatg1** [xyz128189/florr-io-utils#1]
Hello.

Bot detect afk dialog and play sound. But clicks in the wrong position.

**Comment by xyz128189** [comment]
Hi! Thanks for your feedback.
What browser do you use? Do you use any other scripts?
Because it seems to be problem on your side as I have active florr.io tab for 3 hours and still didn't get kicked.

Btw I'll release some bugs fix, make sure you're updated and tell me if your problem persists.

Thanks.

**Comment by jmatg1** [comment]
Google Chrome last version 112.0.5615.138 
I dont use another script/
The update didn't fix the bug
<a href="https://ibb.co/VCJsZ7x"><img src="https://i.ibb.co/gWmxp5d/image.png" alt="image" border="0"></a>

**Comment by xyz128189** [comment]
Thanks for provided information.
I'll test my script in Chrome and will tell you the results. You can try to use a different browser (I use Opera) to see if this is a browser specific problem, if you want to.

**Comment by jmatg1** [comment]
Opera doesn't work either. How do you click this button? What method are you using?

**Comment by xyz128189** [comment]
The script gets button's coordinates and then emulates a click on it.
I plan to add one more method for anti afk later that will work similar to current one, maybe it'll fix your problem

**Comment by xyz128189** [comment]
Hello. I updated the script. Please tell me if your problem is fixed or no.
Thanks.

**Comment by jmatg1** [comment]
<a href="https://ibb.co/WDGfQnd"><img src="https://i.ibb.co/hXLVksn/image.png" alt="image" border="0"></a>
This did not solve the problem, but I found what the problem was. This is due to windows 10 scaling. I'm using a laptop and it has a scale of 125% because of this, the size of the game is different.

I zoomed out the browser by 80% and that solved my problem
