### ISSUE TITLE
New AFK

### ISSUE THREAD

**Issue by jmatg1** [xyz128189/florr-io-utils#2]
Hello. Its me again. Can you make an antiafk for this?
<a href="https://ibb.co/d2w4Hy3"><img src="https://i.ibb.co/9TkHdjf/image.png" alt="image" border="0"></a>

**Comment by xyz128189** [comment]
Hi! It's already in the script, but you can't enable/disable it.

**Comment by jmatg1** [comment]
Its not work for me

**Comment by MrAWAYlol** [comment]
> Hi! It's already in the script, but you can't enable/disable it.

Bro could you make a Discord server and add a bot that notifies you when a Super mob spawns and tells you in which server it's on, like NA or AS? If you already have a Discord server, could you please add a link?📜

**Comment by jmatg1** [comment]
> > Hi! It's already in the script, but you can't enable/disable it.
> 
> Bro could you make a Discord server and add a bot that notifies you when a Super mob spawns and tells you in which server it's on, like NA or AS? If you already have a Discord server, could you please add a link?📜

I made it. But someone need use js script in game for send spawn discrod server
https://discord.gg/JdQD42QZ

**Comment by xyz128189** [comment]
> Its not work for me

I'll check out. Don't have time to work on the script.

**Comment by xyz128189** [comment]
> > Hi! It's already in the script, but you can't enable/disable it.
> 
> Bro could you make a Discord server and add a bot that notifies you when a Super mob spawns and tells you in which server it's on, like NA or AS? If you already have a Discord server, could you please add a link?scroll

Tbh I wanted to create a bot using browser automation, but somehow florr.io detects it and prevents my bot from connecting to the game. I think there's something like captcha, but still I don't have time to investigate it.

**Comment by MrAWAYlol** [comment]
Thx
